### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mmontone** [npapagna/cuis-finder#2]
Hello Nico,

I'm planning to fork this to provide my Popup Morph implementation in a separate repository. 

But I think I need to know how this is licensed to do that. Can you add LICENSE to this repository?

**Comment by npapagna** [comment]
@mmontone done!

Keep in mind that (I think) you don't need to fork the whole repo just to provide a different frontend for Finder.
You can have your own frontend as a separate package and have it configured to be used instead of the default one by configuring it as I do in `FinderWindow class>>configureAsClassFinder`.

I guess that would make your life easier when trying to merge/rebase future changes in this repo.

Also, let me know if you go this route and need any kind of support from this repo. Thanks!

**Comment by mmontone** [comment]
El 26/10/20 a las 16:24, npapagna escribió:
> @mmontone <https://github.com/mmontone> done!
> 
> Keep in mind that (I think) you don't need to fork the whole repo just
> to provide a different frontend for Finder.
> You can have your own frontend as a separate package and have it
> configured to be used instead of the default one by configuring it as I
> do in |FinderWindow class>>configureAsClassFinder|.

Yes. I'm planning to do it like that.

I would like your changeset that implements the "finder selection" in
Event class was integrated into Cuis image, so that no intermediate step
is needed for loading Finder, just Feature require: ...

Do you have in mind doing that?

**Comment by npapagna** [comment]
Sure!

That totally needs to be integrated into Cuis core, it's an ugly hack.
